name: Gitflow-Py Action Pack Version- Main
run-name: Activated by ${{ github.actor }}

on:
  workflow_call:
    inputs:
    
      image_to_use:
        required: true
        type: string
        
      test:
        required: false
        default: 'No'
        type: string

      artifact_rid:
        required: true
        type: string

    secrets:
      NIDAP_TOKEN:
        required: false

jobs: 
  Checking_for_Event_Trigger:
    runs-on: ubuntu-latest
    outputs:
      release_match: ${{ steps.checks.outputs.release_match }}
      dev_match: ${{ steps.checks.outputs.dev_match }}
      pull_check: ${{ steps.checks.outputs.pull_check }}
      main_match: ${{ steps.checks.outputs.main_match }}
      merged_check: ${{ steps.checks.outputs.merged_check }}
    steps:
      - name: Show Job Info
        id: checks
        run: |
          # This is the hub action to decide which action to use
          # After the workflow is being called
          # Print information about the current event
          git --version
          echo "Image to use: ${{ inputs.image_to_use }}"
          echo "Event Branch:  ${{ github.head_ref }}"
          echo "Event Name: ${{ github.event_name }}"
          echo "Pull Merged: ${{ github.event.pull_request.merged }}"
          echo "Pull Request Branch:  ${{ github.base_ref }}"
          
          # Export pass session information to next step. 
          export pull_branch="${{ github.base_ref }}"
          export pull_merged="${{ github.event.pull_request.merged }}"
          export event_name="${{ github.event_name }}"
          export event_branch="${{ github.head_ref }}"
          
          # Determin event triggers, in current version
          # We checkt for pull request status and push event.
          # We also check for dev, release, and main branch.

          if [[ ${{ github.event_name }} == pull_request ]]; then
              echo "pull_check=Yes" >> "$GITHUB_OUTPUT"
              echo "pull_check=Yes"
            else
              echo "pull_check=No" >> "$GITHUB_OUTPUT"
          fi
          
          if [[ -z "$pull_branch" ]]; then
            echo "release_match=No" >> "$GITHUB_OUTPUT"
            echo "main_match=No" >> "$GITHUB_OUTPUT"
          else
            if [[ $pull_branch == release* ]]; then
                echo "release_match=Yes" >> "$GITHUB_OUTPUT"
                echo "release_match=Yes"
            fi
            
            if [[ $pull_branch ==  dev ]]; then
                echo "dev_match=Yes" >> "$GITHUB_OUTPUT"
                echo "dev_match=Yes"
            fi

            if [[ $pull_branch == main ]]; then
              echo "main_match=Yes" >> "$GITHUB_OUTPUT"
              echo "main_match=Yes"
            fi

            if [[ $pull_branch == master ]]; then
              echo "main_match=Yes" >> "$GITHUB_OUTPUT"
              echo "main_match=Yes"
            fi
          fi
          
          if [[ -z "$pull_merged" ]]; then
            echo "merged_check=No" >> "$GITHUB_OUTPUT"
          else
            if [[ $pull_merged == true ]]; then
                echo "merged_check=Yes" >> "$GITHUB_OUTPUT"
                echo "merged_check=Yes"
            fi
          fi
          
  Gitflow_Py_Test:
    needs: [Checking_for_Event_Trigger]
    if: ${{ inputs.test == 'Yes' }}
    uses: fnlcr-dmap/gitflow-py/.github/workflows/test_actions.yml@main

  Check_Pushed_Scripts_version_main:
    needs: [Checking_for_Event_Trigger]
    if: ${{ github.event_name == 'push' && inputs.test == 'No' }}
    uses: fnlcr-dmap/gitflow-py/.github/workflows/check_on_push.yml@main
    with:
      image_to_use: "${{ inputs.image_to_use }}"

  Pull_Request_to_Release_version_main:
    needs: [Checking_for_Event_Trigger]
    if: ${{ needs.Checking_for_Event_Trigger.outputs.pull_check == 'Yes' && 
            needs.Checking_for_Event_Trigger.outputs.merged_check != 'Yes' && 
            needs.Checking_for_Event_Trigger.outputs.release_match == 'Yes' && 
            inputs.test == 'No' }}
    uses: fnlcr-dmap/gitflow-py/.github/workflows/pull_request_to_release.yml@main
    with:
      image_to_use: "${{ inputs.image_to_use }}"
    secrets:
      NIDAP_TOKEN: ${{ secrets.NIDAP_TOKEN }}

  Post_Merged_to_Release_version_main:
    needs: [Checking_for_Event_Trigger]
    if: ${{ needs.Checking_for_Event_Trigger.outputs.pull_check == 'Yes' && 
            needs.Checking_for_Event_Trigger.outputs.merged_check == 'Yes' && 
            needs.Checking_for_Event_Trigger.outputs.release_match == 'Yes' && 
            inputs.test == 'No' }}
    uses: fnlcr-dmap/gitflow-py/.github/workflows/post_merged_to_release.yml@main
    with:
      image_to_use: "${{ inputs.image_to_use }}"
      artifact_rid: "${{ inputs.artifact_rid }}"
    secrets:
      NIDAP_TOKEN: ${{ secrets.NIDAP_TOKEN }}

  Pull_Request_to_Dev_version_main:
    needs: [Checking_for_Event_Trigger]
    if: ${{ needs.Checking_for_Event_Trigger.outputs.pull_check == 'Yes' && 
           needs.Checking_for_Event_Trigger.outputs.merged_check != 'Yes' && 
           needs.Checking_for_Event_Trigger.outputs.dev_match == 'Yes' && 
           inputs.test == 'No' }}
    uses: fnlcr-dmap/gitflow-py/.github/workflows/pull_request_to_dev.yml@main
    with:
      image_to_use: "${{ inputs.image_to_use }}"

  Pull_Request_to_Main_version_main:
    needs: [Checking_for_Event_Trigger]
    if: ${{ needs.Checking_for_Event_Trigger.outputs.pull_check == 'Yes' && 
            needs.Checking_for_Event_Trigger.outputs.merged_check != 'Yes' && 
            needs.Checking_for_Event_Trigger.outputs.main_match == 'Yes' && 
            inputs.test == 'No' }}
    uses: fnlcr-dmap/gitflow-py/.github/workflows/pull_request_to_main.yml@main
    with:
      image_to_use: "${{ inputs.image_to_use }}"

  Post_Processing_for_Merge_to_Main_version_main:
    needs: [Checking_for_Event_Trigger]
    if: ${{ needs.Checking_for_Event_Trigger.outputs.pull_check == 'Yes' && 
            needs.Checking_for_Event_Trigger.outputs.merged_check == 'Yes' && 
            needs.Checking_for_Event_Trigger.outputs.main_match == 'Yes' && 
            inputs.test == 'No' }}
    uses: fnlcr-dmap/gitflow-py/.github/workflows/post_merged_to_main.yml@main
    with:
      image_to_use: "${{ inputs.image_to_use }}"
      artifact_rid: "${{ inputs.artifact_rid }}"
    secrets:
      NIDAP_TOKEN: ${{ secrets.NIDAP_TOKEN }}