name: Gitflow-Py Parser
run-name: Activated by ${{ github.actor }} 

on:
  workflow_call:
    inputs:
    
      image_to_use:
        required: false
        default: ghcr.io/ruiheesi/pyscworkflow:latest
        type: string
      
      verions_to_use:
        required: false
        default: main
        type: string

      artifact_rid:
        required: false
        type: string
        default: 'ri.artifacts.main.repository.00852eef-c60b-4b78-8f14-cd48cdfde051'

      test:
        required: false
        default: No
        type: string

    secrets:
      PAT:
        required: false
      NIDAP_TOKEN:
        required: false
        
jobs:
  Activate_Action_Pack:
    if: ${{ inputs.verions_to_use == 'main' }}
    uses: fnlcr-dmap/gitflow-py/.github/workflows/action_pack_verion_main.yml@main
    with:
      image_to_use: "${{ inputs.image_to_use }}"
      artifact_rid: "${{ inputs.artifact_rid }}"
      test: "${{ inputs.test }}" 
    secrets:
      NIDAP_TOKEN: ${{ secrets.NIDAP_TOKEN }}
